---
config:
  # file that contains the list of items to search for
  list: list
  log_level: INFO
  #API ID and hash 
  api_id: xxxxxx
  api_hash: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  #token:  'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  # days before today to be scraped.
  days_to_scrape: 1
  forward_channel:
    - programma_emanuele
  session: emanuele #name that the .session file will have